name: Build & Publish Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'              # e.g. v7.2.2
  workflow_dispatch:     # manual trigger

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/jaxzin/docker-dsm7-ansible:latest
            ghcr.io/jaxzin/docker-dsm7-ansible:${{ github.ref_name }}
            ghcr.io/jaxzin/docker-dsm7-ansible:${{ github.sha }}